KNN Resgressor : 

1. Import Dataset
2. separate x,y
3. train, test
4. Apply Linear Regression
5. Evaluate Model, Apply KNN Regressor, Evaluate Model

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_excel('Height-Weight1.xlsx')

In [4]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [5]:
df1 = df.copy()
df2 = df.copy()

Data Analysis

In [6]:
df.describe()

Height       Weight
count  8555.000000  8555.000000
mean     66.809925   165.632735
std       3.851454    32.043922
min      54.616858    65.780000
25%      63.957684   139.876803
50%      66.985923   168.521567
75%      69.604427   190.666305
max      80.450000   269.989698

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   object 
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), object(1)
memory usage: 200.6+ KB


In [8]:
df.shape

(8555, 3)

In [9]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [10]:
numeric_columns = df.select_dtypes(include=np.number)
corr_matrix = numeric_columns.corr()
corr_matrix

Height    Weight
Height  1.000000  0.922975
Weight  0.922975  1.000000

# Label Encoder

In [11]:
df.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [12]:
from pandas.api.types import is_numeric_dtype

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in df.columns:
    if is_numeric_dtype(df[col]):
        continue
    else:
        df[col] = le.fit_transform(df[col])
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

# Scaling

In [13]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()

In [14]:
df['Height'] = mm.fit_transform(df[['Height']])

In [15]:
df.head()

Gender    Height      Weight
0       1  0.744399  241.893563
1       1  0.548328  162.310473
2       1  0.754583  212.740856
3       1  0.662487  220.042470
4       1  0.590905  206.349801

# Separate X, Y

In [16]:
x = df.drop('Weight', axis = 1)

In [17]:
x.head()

Gender    Height
0       1  0.744399
1       1  0.548328
2       1  0.754583
3       1  0.662487
4       1  0.590905

In [18]:
y = df[['Weight']]

In [19]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

# Split Train & Test

In [20]:
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression

In [21]:
xtrain,xtest,ytrain,ytest = tts(x,y,test_size=0.3,random_state=78)

In [22]:
xtrain.head()

Gender    Height
2984       1  0.516626
6487       0  0.296121
7243       0  0.284884
6898       0  0.218997
6136       0  0.416769

In [23]:
ytrain.head()

Weight
2984  190.964765
6487  138.381679
7243  141.855825
6898  106.853924
6136  129.375502

In [24]:
xtrain.shape

(5988, 2)

# Applying Linear Regression

In [25]:
ln = LinearRegression()

In [26]:
ln.fit(xtrain,ytrain)

LinearRegression()

In [27]:
pred = ln.predict(xtest)

In [28]:
pred

array([[187.53844321],
       [140.10544754],
       [162.886255  ],
       ...,
       [174.14561879],
       [126.51552617],
       [227.16421198]])

In [29]:
ln.predict([[0,0.356]])

array([[136.45635696]])

# Accuracy, MSE, MAE

In [30]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [31]:
accuracy = r2_score(ytest,pred)

In [32]:
accuracy

0.8999186031764108

In [33]:
mae = mean_absolute_error(ytest,pred)
mae

8.096114041702727

In [34]:
mse = mean_squared_error(ytest,pred)
mse

105.07227399923437

# Visualization 

In [35]:
#plt.scatter(xtrain,ytrain)
xtrain.head()

Gender    Height
2984       1  0.516626
6487       0  0.296121
7243       0  0.284884
6898       0  0.218997
6136       0  0.416769

In [36]:
#xtrain = xtrain.drop('Gender', axis=1)
#xtrain = df.drop('Weight', axis=1)
#xtrain.head

In [37]:
#plt.scatter(xtrain,ytrain)

# Applying KNN Regression

In [38]:
from sklearn.neighbors import KNeighborsRegressor

In [39]:
ne = KNeighborsRegressor()

In [40]:
ne.fit(xtrain, ytrain)

KNeighborsRegressor()

In [41]:
kntest = ne.predict(xtest)
kntest

array([[189.52696512],
       [148.70140594],
       [155.20317956],
       ...,
       [171.85830574],
       [124.34042158],
       [234.2667561 ]])

In [42]:
ne.predict([[0,0.356]])

array([[136.48957828]])

# Evaluate Model

In [43]:
r2_score(ytest,kntest)

0.881850322291756

In [44]:
mse = mean_squared_error(ytest,kntest)
mse

124.0415871789253

In [45]:
mae = mean_absolute_error(ytest,kntest)
mae

8.833802628117647